#ifndef DEFINES_H
#define DEFINES_H

#define MAX_DRIVERS_IN_TEAM 16
#define MAX_TEAMS_IN_SESSION 64

#define KEVS_USAGE_TYPE 	KEVS_USAGE_TYPE_DEFINITION
#define IRACING_USAGE 	 	1
#define SECRET_USAGE 		2

#endif // DEFINES_H